# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.hoeflingsoftware.com.com
title: " Software"
email: andrew@hoeflingsoftware.com
author: Andrew Hoefling
about: >
  <p>Specializing in custom software solutions for projects of any size in the Microsoft Stack of Technology</p>
  <ul>
    <li>Xamarin Mobile Development - Cross Platform Mobile Application Development (iOS, Android, Windows Phone)</li>
    <li>WPF - Windows Desktop Applications</li>
    <li>ASP.NET & ASP.NET MVC - Custom Web Sites and Custom Web Applications</li>
    <li>Microsoft SQL Server</li>
    <li>Azure Cloud Solutions</li>
  </ul>
  <p>I am passionate about Code Quality and believe writing software and architecting software are 2 different skills. I provide software that will stand the test of time an minimize production issues.</p>
copyright: '&copy; 2018 HOEFLING SOFTWARE LLC'
credits: 

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

twitter: https://twitter.com/andrew_hoefling/
linkedin: https://www.linkedin.com/in/andrew-hoefling/
github: https://github.com/ahoefling/
